# Generated by Django 2.2.3 on 2019-09-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
