# Generated by Django 2.2.3 on 2019-09-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphdata', '0002_player_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
