# Generated by Django 2.2.3 on 2019-09-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphdata', '0003_player_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='league',
            field=models.IntegerField(),
        ),
    ]
